/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crucigrama.GUI;

/**
 *
 * @author Kevin Trejos
 */
public class Level extends javax.swing.JDialog {

    /**
     * Creates new form Level
     */
    public Level(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMedium = new javax.swing.JButton();
        btnEasy = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();
        btnVeryHard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setText("Por favor elija el nivel de juego");

        btnMedium.setText("Medio");
        btnMedium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });

        btnEasy.setText("Fácil");
        btnEasy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyActionPerformed(evt);
            }
        });

        btnHard.setText("Difícil");
        btnHard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardActionPerformed(evt);
            }
        });

        btnVeryHard.setText("Muy difícil");
        btnVeryHard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVeryHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeryHardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMedium)
                            .addComponent(btnEasy)
                            .addComponent(btnHard)
                            .addComponent(btnVeryHard))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btnEasy)
                .addGap(18, 18, 18)
                .addComponent(btnMedium)
                .addGap(18, 18, 18)
                .addComponent(btnHard)
                .addGap(18, 18, 18)
                .addComponent(btnVeryHard)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
        //Hacer las acciones para el nivel medio 
        GameWindow gameWindow = new GameWindow(this, true);
        gameWindow.setVisible(true);
    }//GEN-LAST:event_btnMediumActionPerformed

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
        // Hacer las acciones para el nivel fácil
    }//GEN-LAST:event_btnEasyActionPerformed

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
        // Hacer las acciones para el nivel difícil
    }//GEN-LAST:event_btnHardActionPerformed

    private void btnVeryHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeryHardActionPerformed
        // Hacer las acciones para el nivel muy difícil
    }//GEN-LAST:event_btnVeryHardActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnMedium;
    private javax.swing.JButton btnVeryHard;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
